### ISSUE TITLE
mmcv error

### ISSUE THREAD

**Issue by ygt7r21999** [liushuran2/Bayesian_DPA_TISR#1]
Hello! I use pip to install the required package in my exsisting virtual environment like this:
↓↓↓↓↓↓↓↓↓
pip install h5py, matplotlib, mmcv_full, numpy, opencv_python, Pillow, PyYAML, scikit_image, scipy, tifffile, timm, tqdm
↑↑↑↑↑↑↑↑↑

And then I ran:
python test.py --config config.yaml

But error occurs:
↓↓↓↓↓↓↓↓↓
D:\SoftWare\anaconda3\envs\WZH-WS\Lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will r
elease v2.0.0, in which it will remove components related to the training process and add a data transformation modul
e. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
Traceback (most recent call last):
  File "D:\Program\InnovationLAB\Proj_TISR\Bayesian_DPA_TISR-main\test.py", line 19, in <module>
    from mmedit.models.backbones.sr_backbones import DPATISR
  File "D:\Program\InnovationLAB\Proj_TISR\Bayesian_DPA_TISR-main\mmedit\__init__.py", line 30, in <module>
    assert (mmcv_min_version <= mmcv_version <= mmcv_max_version), \
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: mmcv==1.7.2 is used but incompatible. Please install mmcv-full>=(1, 3, 13, 0, 0, 0), <=(1, 6, 0, 0, 0, 0).
↑↑↑↑↑↑↑↑↑

Can you help me?

**Comment by liushuran2** [comment]
It seems to be a mmcv-version problem. Following the 'AssertionError: mmcv==1.7.2 is used but incompatible. Please install mmcv-full>=(1, 3, 13, 0, 0, 0), <=(1, 6, 0, 0, 0, 0).', you might try re-install mmcv with compatible version.

**Comment by liushuran2** [comment]
It seems to be a mmcv-version problem. Following the 'AssertionError: mmcv==1.7.2 is used but incompatible. Please install mmcv-full>=(1, 3, 13, 0, 0, 0), <=(1, 6, 0, 0, 0, 0).', you might try re-install mmcv with compatible version (1.5.0) using 'pip install mmcv==1.5.0'. Actually, 'pip install -r requirements.txt' would help you build correct enviroment!

**Comment by liushuran2** [comment]
It seems to be a mmcv-version problem. Following the 'AssertionError: mmcv==1.7.2 is used but incompatible. Please install mmcv-full>=(1, 3, 13, 0, 0, 0), <=(1, 6, 0, 0, 0, 0).', you might try re-install mmcv with compatible version (1.5.0) using 'pip install mmcv==1.5.0'. 
Actually, 'pip install -r requirements.txt' would help you build correct environment!
